package section15.Q1504;

import java.io.IOException;

public class Main1504 {

    public static void main(String[] args) throws IOException {
        throw new IOException("異常終了します");
    }

}
